### ISSUE TITLE
Home Movie

### ISSUE THREAD

**Issue by iLewisssHD** [joshuaavalon/AvalonXmlAgent.bundle#1]
This Plug-In sounds really cool, but I can't seem to get it to work. Do you have some sort of guide to get it up and running?

**Comment by joshuaavalon** [comment]
What kind of problem are you having? Do not know how to install? or do not know how to create XML?

**Comment by iLewisssHD** [comment]
Hi Joshua,

Apologies for not getting back to you. I put this in just before going on holiday!

So I currently installed the add-on, created a new library called "Test".
Then I have set this to use AvalonXmlAgent as the agent.

Inside the library folder I have a folder called the movies title, inside that folder I have the movie and a .xml file with the example text, where the title and actor are the only filled out lines.

Hope this all makes sense.

Lewis

**Comment by joshuaavalon** [comment]
Please read the [wiki](https://github.com/joshuaavalon/AvalonXmlAgent.bundle/wiki/File-Format) and check if you have meet all the requirements:

1. If it is a movie, it should be `<moive name> (<year>).xml`
2. Does the file follow the [format](https://github.com/joshuaavalon/AvalonXmlAgent.bundle/wiki/File-Format#movie-1)?

**Comment by iLewisssHD** [comment]
I did try it like that previously and it didn't work.

I have just tried it again as the following.

Folder called Test (2019)
Inside are: 
Test (2019).xml
Test (2019).mp4

The xml file contains:
```
<movie>
    <title>Test (2019)</title>
    <originaltitle></originaltitle>
    <sorttitle></sorttitle>
    <set></set>
    <rating></rating>
    <premiered></premiered>
    <plot></plot>
    <tagline></tagline>
    <mpaa></mpaa>
    <genre></genre>
    <writer></writer>
    <studio></studio>
    <director></director>
    <actor>
        <name>Test Actor</name>
        <role>1</role>
        <thumb>https://i.imgur.com/aEKiDlB.jpg</thumb>
    </actor>
</movie>
```

**Comment by joshuaavalon** [comment]
Please try the following:

1. Go to the movie > More > Fix Match...
2. Does it show any title? If it is working, it should show `Test (2019) 100%`
3. If no, please share `/<Plex Folder>/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.avalonxml.log`

**Comment by iLewisssHD** [comment]
Nope nothing comes up when I try to match the content.

Please see attached.
[com.plexapp.agents.avalonxml.log](https://github.com/joshuaavalon/AvalonXmlAgent.bundle/files/3381719/com.plexapp.agents.avalonxml.log)

**Comment by joshuaavalon** [comment]
> 2019-07-11 12:10:53,022 (7f88b57fa700) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'Avalon XML Movie Agent', called with keyword arguments {'openSubtitlesHash': '008bb6d378da7b92', 'name': 'Test', 'year': '2019', 'filename': '%2Fhome%2Fmedia%2FTest%2FTest%20(2019)%2FTest%20(2019)%2Emp4', 'plexHash': '8b3d40a5b31b5d6ceadc41a6b2b60b6e0d3c9e28', 'duration': '934563', 'id': '2705'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-158e5b199/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/AvalonXmlAgent.bundle/Contents/Code/__init__.py", line 137, in search
    movie_xml = MovieXml(root_element)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/AvalonXmlAgent.bundle/Contents/Code/xml.py", line 262, in __init__
    self.year = self.originally_available_at.year  # type: int
AttributeError: 'NoneType' object has no attribute 'year'

The date parsing throw error. Try to set `releasedate` to `2019-01-01`.

**Comment by iLewisssHD** [comment]
Do you mean within Plex or the .xml file?

As the .xml file does not have a releasedate line.

**Comment by iLewisssHD** [comment]
Adding the releasedate in the XML worked.

Thanks so much!

**Comment by iLewisssHD** [comment]
Is there anyway to not have the year in the title?

For some of the content it is unknown or not necessary

**Comment by joshuaavalon** [comment]
> Is there anyway to not have the year in the title?

You can remove it and lock it inside Plex.

**Comment by iLewisssHD** [comment]
I’m assuming that would be on a per movie basis?

**Comment by joshuaavalon** [comment]
Yes. The problem when I was writing agent, I follow the recommendation from Plex for file naming. Also, the scanning file is handled by another agent from Plex.

If you want to remove the year completely, you have to change the agent code and test it yourself.

**Comment by iLewisssHD** [comment]
That makes sense, thanks.

One last thing, I am struggling to get local actor thumbnails working. It works fine if I upload a picture to Imgur and enter the URL.
Are their any specifications that the image needs to meet?

**Comment by joshuaavalon** [comment]
To use local actor thumbnails, you have to set `Find image from actor folder if thumb is not define. (Empty to disable)` in agent setting. Note that setting of an agent is shared across libraries.

The naming should be `<name>.<ext>`.

Also, I found out it is bugged. =P  I fixed it with 41b4f1eca7d3db7718372d11b47c795b413c06cc . It will use local image if it is not set in XML.

**Comment by iLewisssHD** [comment]
Thanks I have just updated the plug-in. 

So I have set the Agent to the path e.g: /home/media/metadata/actor/

Then in the .xml file I have just put:
`<thumb>test_actor.jpg</thumb>`

And it isn't working, I have made sure permissions are okay by setting them to 777 for the directory and file.

It is not a big problem as I can upload them to Imgur and put the url. But it would be interesting to know why it isn't working locally.

**Comment by joshuaavalon** [comment]
You miss understand  how it works. `thumb` is only for URL.

For example,

```xml
<actor>
    <name>Foo</name>
    <role>Role 1</role>
    <thumb>https://example.com/cast/Foo.jpg</thumb>
</actor>
<actor>
    <name>Bar</name>
    <role>Role 2</role>
</actor>
```

`Foo` will use `https://example.com/cast/Foo.jpg`.
`Bar` will use `/home/media/metadata/actor/Bar.jpg`. (or any support extensions)

Also, note that Plex only support 1 thumbnail per actor. For example, you set `Foo` to `https://example.com/cast/Foo.jpg` in Movie 1 and set `Foo` to `https://example.com/cast/Foo2.jpg` in Movie 2. The later updated one will overwrite.

**Comment by iLewisssHD** [comment]
Thank you

But I still can't seem to get the local image working. 
I have added the path in the agents settings. Then just removed the thumb line and made sure that the image is the same name as the actor.

**Comment by iLewisssHD** [comment]
It is acting as if it has found it because it doesn't have TA written in the actors picture anymore. But it isn't showing the picture either, its just a blank greyish circle.

**Comment by joshuaavalon** [comment]
Just ignore that function for now.

**Comment by rs6060** [comment]
Hi Joshua

First I have to say this plugin is awesome, it saved me the agro of coding my own version as it does exactly what I wanted it to.  I have one minor issue.  Once I have added an actors thumbnail and refreshed the Meta Data, if I choose to change that image, keeping the same filename, it is not updating the image and still showing the old one, which I am guessing it caches locally.  Is there a way for me to force the image change, without having to create a new image with a new name?

**Comment by joshuaavalon** [comment]
@rs6060 There is may be two reason lead to this.

1. This agent is using URL as key. A new image should have a new URL. It should update on refresh metadata.
2. From my observation, Plex is caching actor image by name. This mean if you have the following,

* Show A: Actor A (Image 1)
* Show B: Actor A (Image 2)

The latest one that refresh metadata will overwrite the other.

**Comment by rs6060** [comment]
Hi Joshua

I appears that this isn't working for me.  So as url/file1.jpg, I used and image. I decide to change that image and write over file1.jpg.  The image on the thumbnail still remains from the first version. So I am guessing the image is cached and not over written

**Comment by rs6060** [comment]
Hi Joshua

I have been investigating this issue further.

Could you just confirm the following.  The image is pulled from the URL but is then stored locally within the bundle, and only reloads if a different URL is used?

If so, is there anyway of clearing these local images from the bundle?

**Comment by rs6060** [comment]
Hi Joshua

For some reason I am having a problem with a movie I have added last night and the plugin does not seem to want to work,  Up until this point I haven't had any issues.  I have spent an hour checking the filenames, year data and the full XML file and can not see any issues.  The agent doesn't seem to be picking up any data from the XML file.  This is the log file, could you advise?


2020-05-14 07:31:52,598 (27e4) :  DEBUG (runtime:88) - Sending packed state data (109 bytes)
2020-05-14 07:31:52,598 (27e4) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2020-05-14 07:32:47,423 (d6c) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.avalonxml/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU3CnMxNgo1MzIyMTFlZDRiYTFjMmU5czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczExCkhhdmFuYSBCbGV1czQKbmFtZXM0CjIwMTlzNAp5ZWFyczEzMQpXJTNBJTVDU2hhcmVkJTIwQWR1bHQlNUNCYW5nJTIwT3JpZ2luYWxzJTVDUHJldHR5JTIwYW5kJTIwUmF3JTVDSGF2YW5hJTIwQmxldSUyMCUyODIwMTklMjklNUNoYXZhbmEtYmxldS1zY2VuZS0xJTIwJTI4MjAxOSUyOSUyRW1wNHM4CmZpbGVuYW1lczQwCjhiODg0YzY3M2I0YzVkYjNjM2U5N2EzYjI2OTliZGQ4OWViNzNlNmVzOApwbGV4SGFzaHM3CjIwNjcxMTNzOApkdXJhdGlvbnM0CjQ5MjlzMgppZHIwCg__
2020-05-14 07:32:47,424 (d6c) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-05-14 07:32:47,424 (d6c) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.avalonxml/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU3CnMxNgo1MzIyMTFlZDRiYTFjMmU5czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczExCkhhdmFuYSBCbGV1czQKbmFtZXM0CjIwMTlzNAp5ZWFyczEzMQpXJTNBJTVDU2hhcmVkJTIwQWR1bHQlNUNCYW5nJTIwT3JpZ2luYWxzJTVDUHJldHR5JTIwYW5kJTIwUmF3JTVDSGF2YW5hJTIwQmxldSUyMCUyODIwMTklMjklNUNoYXZhbmEtYmxldS1zY2VuZS0xJTIwJTI4MjAxOSUyOSUyRW1wNHM4CmZpbGVuYW1lczQwCjhiODg0YzY3M2I0YzVkYjNjM2U5N2EzYjI2OTliZGQ4OWViNzNlNmVzOApwbGV4SGFzaHM3CjIwNjcxMTNzOApkdXJhdGlvbnM0CjQ5MjlzMgppZHIwCg__
2020-05-14 07:32:47,424 (d6c) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '532211ed4ba1c2e9', 'name': 'Havana Bleu', 'year': '2019', 'filename': 'W%3A%5CShared%20Adult%5CBang%20Originals%5CPretty%20and%20Raw%5CHavana%20Bleu%20%282019%29%5Chavana-bleu-scene-1%20%282019%29%2Emp4', 'plexHash': '8b884c673b4c5db3c3e97a3b2699bdd89eb73e6e', 'duration': '2067113', 'id': '4929'}
2020-05-14 07:32:47,427 (d6c) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/4929/tree'
2020-05-14 07:32:47,433 (d6c) :  DEBUG (logkit:13) - ==================== Search Start ====================
2020-05-14 07:32:47,434 (d6c) :  DEBUG (logkit:13) - Avalon XML Movie Agent (2.0.0)
2020-05-14 07:32:47,434 (d6c) :  DEBUG (logkit:13) - Plex version: 1.19.2.2673-776106bc6
2020-05-14 07:32:47,434 (d6c) :  INFO (logkit:16) - Search for Havana Bleu
2020-05-14 07:32:47,460 (d6c) :  CRITICAL (core:574) - Exception in the search function of agent named 'Avalon XML Movie Agent', called with keyword arguments {'openSubtitlesHash': '532211ed4ba1c2e9', 'name': 'Havana Bleu', 'year': '2019', 'filename': 'W%3A%5CShared%20Adult%5CBang%20Originals%5CPretty%20and%20Raw%5CHavana%20Bleu%20%282019%29%5Chavana-bleu-scene-1%20%282019%29%2Emp4', 'plexHash': '8b884c673b4c5db3c3e97a3b2699bdd89eb73e6e', 'duration': '2067113', 'id': '4929'} (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-776106bc6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "C:\Users\rs606\Desktop\Plex Media Server\Plug-ins\AvalonXmlAgent.bundle\Contents\Code\__init__.py", line 127, in search
    root_element = get_movie_xml(media)
  File "C:\Users\rs606\Desktop\Plex Media Server\Plug-ins\AvalonXmlAgent.bundle\Contents\Code\helper.py", line 103, in get_movie_xml
    return XML.ElementFromString(xml_str)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-776106bc6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\parsekit.py", line 301, in ElementFromString
    return self._core.data.xml.from_string(string, encoding = encoding)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-776106bc6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\data.py", line 162, in from_string
    return etree.fromstring(markup, parser=(xml_parser if remove_blank_text else None))
  File "lxml.etree.pyx", line 2743, in lxml.etree.fromstring (lxml-2.3\src\lxml\lxml.etree.c:52665)
  File "parser.pxi", line 1573, in lxml.etree._parseMemoryDocument (lxml-2.3\src\lxml\lxml.etree.c:79932)
  File "parser.pxi", line 1452, in lxml.etree._parseDoc (lxml-2.3\src\lxml\lxml.etree.c:78774)
  File "parser.pxi", line 960, in lxml.etree._BaseParser._parseDoc (lxml-2.3\src\lxml\lxml.etree.c:75389)
  File "parser.pxi", line 564, in lxml.etree._ParserContext._handleParseResultDoc (lxml-2.3\src\lxml\lxml.etree.c:71739)
  File "parser.pxi", line 645, in lxml.etree._handleParseResult (lxml-2.3\src\lxml\lxml.etree.c:72614)
  File "parser.pxi", line 585, in lxml.etree._raiseParseError (lxml-2.3\src\lxml\lxml.etree.c:71955)
XMLSyntaxError: xmlParseEntityRef: no name, line 2, column 20

2020-05-14 07:32:47,461 (d6c) :  DEBUG (runtime:88) - Sending packed state data (109 bytes)
2020-05-14 07:32:47,461 (d6c) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
